[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
add_one = { path = "../add_one" }
lsclone = { path = "../lsclone" }
structopt = "0.3.26"
